[package]
name = "studio_project_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
uuid = { version = "1.8.0", features = ["v4"] }
elementtree = "1.2.3"
flate2 = "1.0.30"
zune-inflate = "0.2.54"
colored = "2.1.0"
xml = "0.8.20"
quick-xml = "0.31.0"
log = "0.4.21"
anyhow = "1.0.83"
env_logger = "0.11.3"
crc32fast = "1.4.0"
thiserror = "1.0.60"