# config.toml

# if you change this file while the program is running, you need to restart the program for changes to take effect.
# TODO: Add support for multiple project folders

paths = [
    'C:\Users\judee\Documents\Projects\band with joel'
]

# use {USER_HOME} as a shortcut to your user folder

database_path = '{USER_HOME}\Documents\ableton_manager\ableton_live_sets.db'

live_database_dir = '{USER_HOME}\AppData\Local\Ableton\Live Database'