# config.toml

# if you change this file while the program is running, you need to restart the program for changes to take effect.
# TODO: Add support for multiple project folders

paths = [
    'C:\Users\judee\Documents\Projects\90s'
]

# use {USER_HOME} as a shortcut to your user folder

database_path = '{USER_HOME}\RustroverProjects\studio_project_manager\live_set_db_test_dir\ableton_live_sets.db'

live_database_dir = '{USER_HOME}\AppData\Local\Ableton\Live Database'