# config.toml

# if you change this file while the program is running, you need to restart the program for changes to take effect.

paths = [
    'C:\Users\judee\Documents\Projects',
    'E:\Music Creation'
]

# use {USER_HOME} as a shortcut to your user folder

# Database configuration
# If database_path is not specified or empty, it will default to the executable's directory
# database_path = '{USER_HOME}\RustroverProjects\studio_project_manager\live_set_db_test_dir\ableton_live_sets.db'

live_database_dir = '{USER_HOME}\AppData\Local\Ableton\Live Database'

# gRPC server configuration
grpc_port = 50051

# Logging configuration
# Options: error, warn, info, debug, trace
log_level = "error"

# Media storage configuration
media_storage_dir = '{USER_HOME}\AppData\Local\StudioProjectManager\media'

# Media file size limits (in MB)
max_cover_art_size_mb = 10
max_audio_file_size_mb = 50

# Allowed file formats
allowed_image_formats = ["jpg", "jpeg", "png", "webp"]
allowed_audio_formats = ["mp3", "wav", "m4a", "flac"]